name: deploy-html-changes
run-name: deploying changes to index.html
on:
  push:
    paths:
      - '**.html'
  workflow_dispatch:
    

jobs:
  setup:
    name: building site
    runs-on: ubuntu-latest
    steps:
      - name: setup pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
 
      - name: upload pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3	
        with:
          path: "github-deployment-test1"
          
  deploy_site:
    if: github.ref == 'refs/heads/main'
    needs: setup
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploying site changes
        id: deployment
        uses: actions/deploy-pages@v4
      
    
